spring:
  jpa:
    show-sql: false
    
  security:
    user:
      password: secret
    saml2:
      relyingparty:
        registration:
          product-app:
            entity-id: "product-app"
            signing:
              credentials:
                - private-key-location: classpath:config/rp-key.key
                  certificate-location: classpath:config/rp-certificate.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: "http://localhost:8081/realms/product-realm/protocol/saml/descriptor"


appli:
  jwt:
    secretKey: t3fJ6MlW5FjioNiCoaW8z814ezL38dt3fJ6MlW5FjioNiCoaW8z814ezL38dt3fJ6MlW5FjioNiCoaW8z814ezL38d
    validity: 1000
    rememberMe: 1000
    
logging:
  level:
    org.springframework.security: DEBUG
  
management:
  endpoints:
    web:
      exposure:
        include: "*"