
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: route-order
          uri: http://localhost:8082
          predicates:
            - Path= /order/**
          filters:
            - RewritePath=/order/?(?<remaining>.*), /$\{remaining}

      

management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - beans
        - health
        - metrics
        - httptrace
        - refresh
        - gateway
        - prometheus
  endpoint:
    health:
      show-details: always

        
logging:
  level:
    '[org.springframework]': debug
    
    
     